# Generated by Django 4.1.1 on 2022-11-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notify',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
    ]
