# Generated by Django 4.1.1 on 2022-11-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_category_task_priority_task_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('HOMEWORK', 'HOMEWORK'), ('GROUPWORK', 'GROUPWORK'), ('WORKSTUDY', 'WORKSTUDY')], default='', max_length=45),
        ),
    ]
